import sys
import os
import asyncio
from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService

# Ensure root directory in path for relative imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from app.agents.search_agent import search_agent
from app.agents.upload_agent import upload_agent
from app.agents.recommend_agent import recommend_agent

# Session service shared by sub-agents
sub_agent_session_service = InMemorySessionService()

async def _call_sub_agent(agent: Agent, query: str) -> str:
    """Helper function to execute a sub-agent asynchronously and return its final text output."""
    runner = Runner(agent=agent, session_service=sub_agent_session_service)
    
    # Create or reuse a conversation session for this agent
    session = await sub_agent_session_service.create_session(
        app_name="router_super",
        user_id="router_agent",
        session_id=f"session_for_{agent.name}"
    )
    
    response_parts = []
    try:
        async for event in runner.run_async(
            user_id="router_agent",
            session_id=session.id,
            new_message=query
        ):
            if event.is_final_response() and event.content and event.content.parts:
                response_parts.append(event.content.parts[0].text)
        
        return "".join(response_parts) if response_parts else "No response generated by specialist."
    except Exception as e:
        return f"Error executing specialist {agent.name}: {str(e)}"

# Define routing delegate tools
async def delegate_to_search_agent(query: str) -> str:
    """Use this tool to find notes, past exams, study documents, list available courses, or see popular materials.
    
    Args:
        query: The search request or natural language query (e.g. 'find past exams for MATH101').
    """
    return await _call_sub_agent(search_agent, query)

async def delegate_to_upload_agent(query: str) -> str:
    """Use this tool to index files, create assignment reminders, join study groups, or list study groups/deadlines.
    
    Args:
        query: The instruction containing details to register, upload, or create group/deadline events.
    """
    return await _call_sub_agent(upload_agent, query)

async def delegate_to_recommend_agent(query: str) -> str:
    """Use this tool to find and recommend related documents based on what a student is currently studying or viewing.
    
    Args:
        query: Recommendation query containing title or course code context.
    """
    return await _call_sub_agent(recommend_agent, query)

# Define Router Agent
router_agent = Agent(
    name="router_agent",
    model="gemini-2.5-flash",
    instruction=(
        "You are the main coordinator and Router Agent for the University Chatbot. "
        "Your role is to understand user requests and delegate them to the appropriate specialist agent. "
        "- For search-related requests (finding notes, exams, listing courses, popular documents), call delegate_to_search_agent. "
        "- For indexing uploads, creating assignment deadlines, showing deadlines, joining/creating study groups, call delegate_to_upload_agent. "
        "- For content recommendations (suggesting next resources, similar materials), call delegate_to_recommend_agent. "
        "Explain to the user briefly what you are doing (e.g. 'I am routing your request to our search specialist...') "
        "and present the specialist's response as the final answer. "
        "If the user query is a simple greeting, greet them back warmly and explain what you can help with."
    ),
    tools=[
        delegate_to_search_agent,
        delegate_to_upload_agent,
        delegate_to_recommend_agent
    ]
)

if __name__ == "__main__":
    # Diagnostic interactive run for the router coordinator
    from google.adk.sessions import InMemorySessionService
    
    async def main():
        session_service = InMemorySessionService()
        runner = Runner(agent=router_agent, session_service=session_service)
        session = await session_service.create_session("app", "test_user", "test_session")
        print("Router Agent ready. Enter request (e.g. 'find calculus notes' or 'list deadlines'):")
        while True:
            try:
                user_input = input("> ")
                if user_input.lower() in ("exit", "quit"):
                    break
                async for event in runner.run_async("test_user", session.id, user_input):
                    if event.is_final_response() and event.content and event.content.parts:
                        print(event.content.parts[0].text)
            except KeyboardInterrupt:
                break
                
    asyncio.run(main())
